version: '3'

volumes:
  postgres_data: {}

services:
  application:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: shmango_app
    depends_on:
      - postgres
      - redis
    env_file:
      - compose.env

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 9999:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0
